language: python
python:
  - "3.6"  

addons:
  apt_packages:
    - swig-3.0.12
  
# command to install dependencies
install:
  - pip install -r requirements.txt
  - python setup.py bdist_wheel
  - python setup.py install
         
# command to run tests
          
