language: python
python:
  - "3.6"  

env:
  global 
  - MINICONDA_URL="https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh"

before_install:
  - wget $MINICONDA_URL -O miniconda.sh
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - if [[ `which conda` ]]; then echo 'Conda installation successful'; else exit 1; fi
  - conda create -n testenv --yes python=$PYTHON_VERSION pip wheel swig numpy scikit-learn pytest
  - source activate testenv

# command to install dependencies
install:
  - pip install -r requirements.txt
  - python setup.py bdist_wheel
  - python setup.py install
         
# command to run tests
script:
  - source activate testenv
  - python -m pytest
