language: python
python:
  - "3.6"  
  
# command to install dependencies
install:
  - brew install swig
  - pip install -r requirements.txt
  - python setup.py bdist_wheel
  - python setup.py install
         
# command to run tests
          
